import { useEffect, useState } from "react";
import { getFamilies } from "../../services/familyService";
import { addWorkEntry, deleteWorkEntry, subscribeWorkEntries, updateWorkEntry } from "../../services/workService";
const blank = { familyId: "", family: "", date: new Date().toISOString().slice(0, 10), hours: "", note: "" };
export default function Work() {
  const [families, setFamilies] = useState([]), [entries, setEntries] = useState([]), [form, setForm] = useState(blank), [editing, setEditing] = useState(null);
  useEffect(() => { getFamilies().then(setFamilies); return subscribeWorkEntries(setEntries); }, []);
  async function submit(e) { e.preventDefault(); if (!form.familyId || !Number(form.hours)) return alert("Vyberte rodinu a zadejte počet hodin."); const data = { ...form, hours: Number(form.hours) }; if (editing) await updateWorkEntry(editing, data); else await addWorkEntry(data); setForm(blank); setEditing(null); }
  function edit(entry) { setEditing(entry.id); setForm({ familyId: entry.familyId, family: entry.family, date: entry.date, hours: entry.hours, note: entry.note ?? "" }); }
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Brigády</h1><p className="text-slate-500">Evidence odpracovaných hodin jednotlivých rodin.</p></div><div className="rounded-xl bg-white p-6 shadow"><h2 className="mb-4 text-xl font-semibold">{editing ? "Upravit brigádu" : "Nový záznam"}</h2><form onSubmit={submit} className="grid gap-4 md:grid-cols-4"><select required className="rounded border p-3" value={form.familyId} onChange={(e) => { const family = families.find((item) => item.id === e.target.value); setForm({ ...form, familyId: e.target.value, family: family?.name ?? "" }); }}><option value="">Rodina</option>{families.filter((item) => item.active !== false).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input required type="date" className="rounded border p-3" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /><input required min="0.5" step="0.5" type="number" placeholder="Hodin" className="rounded border p-3" value={form.hours} onChange={(e) => setForm({ ...form, hours: e.target.value })} /><button className="rounded bg-blue-600 px-5 font-semibold text-white">{editing ? "Uložit" : "Přidat"}</button><textarea className="rounded border p-3 md:col-span-3" rows="2" placeholder="Popis práce (nepovinné)" value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} />{editing && <button type="button" onClick={() => { setEditing(null); setForm(blank); }} className="rounded border px-5">Zrušit</button>}</form></div><div className="overflow-x-auto rounded-xl bg-white shadow">{entries.length ? <table className="w-full"><thead className="bg-slate-100"><tr><th className="p-3 text-left">Datum</th><th className="p-3 text-left">Rodina</th><th className="p-3 text-right">Hodin</th><th className="p-3 text-left">Popis</th><th className="p-3">Akce</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} className="border-t"><td className="p-3">{entry.date}</td><td className="p-3 font-medium">{entry.family}</td><td className="p-3 text-right">{entry.hours}</td><td className="p-3">{entry.note}</td><td className="p-3 text-center"><button onClick={() => edit(entry)} className="mr-3 text-blue-700 hover:underline">Upravit</button><button onClick={() => window.confirm("Smazat záznam brigády?") && deleteWorkEntry(entry.id)} className="text-red-700 hover:underline">Smazat</button></td></tr>)}</tbody></table> : <p className="p-8 text-center text-slate-500">Zatím nejsou zapsané žádné brigády.</p>}</div></div>;
}
